# Название проекта
name: KinescopeExample
options:
  # Версия Xcode
  xcodeVersion: 12.4
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
settings:
  DEVELOPMENT_TEAM: EFAAG9GXN4
targets:
    KinescopeExample:
      dependencies:
        - sdk: UIKit.framework
      type: application
      platform: iOS
      deploymentTarget: 10.0
      scheme:
        configVariants: all
      sources:
        - path: KinescopeExample
      info:
        path: KinescopeExample/Application/Info.plist
        properties:
          UILaunchStoryboardName: LaunchScreen
          UIMainStoryboardFile: Main
          CFBundleName: KinescopeExample
          CFBundleShortVersionString: $(MARKETING_VERSION)
          CFBundleVersion: $(CURRENT_PROJECT_VERSION)
          UIBackgroundModes: [audio,airplay,and_picture_in_picture]
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: io.kinescope.example
          MARKETING_VERSION: "0.1"
          CURRENT_PROJECT_VERSION: 0
          VERSIONING_SYSTEM: "apple-generic"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
          CODE_SIGN_IDENTITY: "iPhone Developer"
          CODE_SIGN_STYLE: Automatic
          EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
