# Название проекта
name: KinescopeSDK
options:
  # Версия Xcode
  xcodeVersion: 12.4
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
targets:
    KinescopeSDK:
      dependencies:
        - sdk: UIKit.framework
        - sdk: AVFoundation.framework
        - sdk: AVKit.framework
      type: framework
      platform: iOS
      deploymentTarget: 10.0
      scheme:
        configVariants: all
        testTargets: [KinescopeSDKTests]
      sources:
        - path: KinescopeSDK
      info:
        path: KinescopeSDK/Info.plist
        properties:
          CFBundleName: KinescopeSDK
          CFBundleShortVersionString: $(MARKETING_VERSION)
          CFBundleVersion: $(CURRENT_PROJECT_VERSION)
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: io.kinescope.sdk
          MARKETING_VERSION: "0.1"
          CURRENT_PROJECT_VERSION: 0
          VERSIONING_SYSTEM: "apple-generic"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
          CODE_SIGN_IDENTITY: "iPhone Developer"
          CODE_SIGN_STYLE: Automatic
          EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"

    KinescopeSDKTests:
      type: bundle.unit-test
      platform: iOS
      deploymentTarget: 10.0
      scheme:
        configVariants: all
      sources: [KinescopeSDKTests]
      info:
        path: KinescopeSDKTests/Info.plist
        properties: []
      dependencies:
        - target: KinescopeSDK
      settings:
        configs:
          Debug:
            EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
